### ISSUE TITLE
Getting Started/The Tangle/Immutability - Bug in repl.it hashing example

### ISSUE THREAD

**Issue by VladTheRul4r** [iotaledger/documentation#861]
There is a small bug in the "Immutability" chapter ( https://docs.iota.org/docs/getting-started/1.1/the-tangle/immutability / https://github.com/iotaledger/documentation/blob/master/getting-started/1.1/the-tangle/immutability.md ). The repl.it example  ( https://repl.it/@jake91/hashing-example?lite=true#index.js ) in the section "Understanding hashing algorithms" is not working correctly. When you copy the code into a local file and run it, it works. If you press "Run" in repl.it, you get the following error:

Error: Invalid trits
    at Object.trytes (/home/runner/pe22DXuZ7r0/node_modules/@iota/converter/out/converter/src/trits.js:117:15)
    at hash (/home/runner/pe22DXuZ7r0/index.js:21:25)
    at /home/runner/pe22DXuZ7r0/index.js:24:1
    at Script.runInContext (vm.js:130:18)
    at Object.<anonymous> (/run_dir/interp.js:209:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

**Comment by jspdown** [comment]
There seems to be a bug in Repl.it. The issue comes from the execution of `Converter.tritsToTrytes(output)`. `tritsToTrytes` throws an error if `output instanceof Int8Array` is false.

 Apparently, the `Int8Array` type used in the test file and the one from the `@iota/converter` are different. It's like if Repl.it was redefining this object in each unit.

I managed to isolate the issue in the following Repl.it test: https://repl.it/join/drjicuxg-jspdown

**Comment by jspdown** [comment]
I reported the issue on https://repl.it/bugs/p/js-instanceof-int8array. It's under investigation on their side.
